---
- name: Debug
  ansible.builtin.debug:
    msg: Host [{{ inventory_hostname }}]

- include_tasks: update_all.yml

- include_tasks: install_list.yml
  vars:
    list:
      - ntp
      - monit
      - default-jre 
      - elasticsearch
      - logstash
