---
- name: Debug
  ansible.builtin.debug:
    msg: Host {{ inventory_hostname }}.

- name: Pass elasticsearch config
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_conf}}"

- name: Enable elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    masked: no

- name: Start elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: true
